name: Firebase Hosting

on:
  push:
    branches: [master, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies and build
        run: |
          yarn
          yarn build

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          firebase deploy --only hosting:development \
            --non-interactive \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/master'
        run: |
          firebase deploy --only hosting:prod \
            --non-interactive \
            --token "${{ secrets.FIREBASE_TOKEN }}" \
            -m "RunID ${{ github.run_id }} Commit SHA ${{ github.sha }}"
