name: Deploy to Firebase Hosting (DEV / PROD)

on:
  push:
    branches:
      - dev
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci && npm run build

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/dev'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PRODUCT_D3789 }}
          channelId: dev
          projectId: test-product-d3789
          target: dev

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/master'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PRODUCT_D3789 }}
          channelId: live
          projectId: test-product-d3789
          target: prod
