name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Виконуємо деплой на основну гілку

jobs:
  deploy:
    runs-on: ubuntu-latest # Використовуємо Ubuntu як середовище для виконання

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Використовуємо Node.js 16

      - name: Install dependencies
        run: |
          npm install -g firebase-tools  # Встановлюємо Firebase CLI глобально
          npm install  # Встановлюємо інші залежності

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}  # Виконуємо деплой
